# Generated by Django 3.1 on 2020-08-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginauthenticate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauthenticate',
            name='begin_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
